"""Shared pytest configuration for the organized test suites."""

import sys
from pathlib import Path


# Keep the distributable source tree free of generated bytecode during tests.
sys.dont_write_bytecode = True

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_ROOT = REPOSITORY_ROOT / "runtime"

# Production modules have one source of truth: the distributable runtime bundle.
if str(RUNTIME_ROOT) not in sys.path:
    sys.path.insert(0, str(RUNTIME_ROOT))

# Repository-only checks remain importable after the production runtime path.
if str(REPOSITORY_ROOT) not in sys.path:
    sys.path.insert(1, str(REPOSITORY_ROOT))
