using System;
using System.Collections.Generic;
using System.Linq;

namespace ShadowCore;

public sealed class SolarSampleV0 { public int SampleIndex {get;set;} public double TrueSolarMinutes {get;set;} public double SolarAltitudeDeg {get;set;} public double SolarAzimuthDeg {get;set;} public double ShadowAzimuthTrueNorthDeg {get;set;} public double ShadowAzimuthModelDeg {get;set;} public double ShadowLengthFactor {get;set;} public Point2M ShadowDirectionModel {get;set;} = new Point2M(); }
public sealed class SolarResultV0 { public bool Available {get;set;} public bool Complete {get;set;} public string Method {get;set;}="explicit_declination_true_solar_v0"; public IList<SolarSampleV0> Samples {get;set;}=new List<SolarSampleV0>(); public IList<string> Blockers {get;set;}=new List<string>(); public IList<string> Warnings {get;set;}=new List<string>(); public bool PermitReadyCertified=>false; }
public sealed class ShadowPolygonV0 { public int ComponentIndex=>0; public string Role=>"outer"; public bool Closed=>true; public string Method=>"compiled_convex_prism_projection_v0"; public IList<Point2M> PointsM {get;set;}=new List<Point2M>(); }
public sealed class ShadowSliceV0 { public int SliceIndex {get;set;} public double TrueSolarMinutes {get;set;} public bool Complete=>true; public IList<ShadowPolygonV0> Polygons {get;set;}=new List<ShadowPolygonV0>(); }
public sealed class ShadowSlicesResultV0 { public bool Available {get;set;} public bool Complete {get;set;} public string Method=>"compiled_convex_prism_projection_v0"; public IList<ShadowSliceV0> Slices {get;set;}=new List<ShadowSliceV0>(); public IList<string> Blockers {get;set;}=new List<string>(); public IList<string> Warnings {get;set;}=new List<string>(); public bool PermitReadyCertified=>false; }
public sealed class GridSpecV0 { public double OriginXM {get;set;} public double OriginYM {get;set;} public double ResolutionM {get;set;} public int XCount {get;set;} public int YCount {get;set;} public string Ordering=>"row_major_y_then_x"; public double MaxXM {get;set;} public double MaxYM {get;set;} }
public sealed class DurationPointV0 { public double X {get;set;} public double Y {get;set;} public double ShadowDurationMinutes {get;set;} }
public sealed class DurationResultV0 { public bool Available {get;set;} public bool Complete {get;set;} public string Method=>"grid_trapezoidal_time_integration_v1"; public double? TemporalStepMinutes {get;set;} public double SpatialResolutionM {get;set;} public int GridPointCount {get;set;} public double MaximumShadowDurationMinutes {get;set;} public int ShadowedPointCount {get;set;} public GridSpecV0? GridSpec {get;set;} public IList<DurationPointV0> DurationValues {get;set;}=new List<DurationPointV0>(); public IList<string> Blockers {get;set;}=new List<string>(); public IList<string> Warnings {get;set;}=new List<string>{"Duration values are a grid/trapezoidal numerical approximation at the configured temporal interval."}; public bool PermitReadyCertified=>false; }
public sealed class ContourV0 { public double LevelMinutes {get;set;} public int ContourIndex {get;set;} public bool Closed {get;set;} public int PointCount=>PointsM.Count; public double LengthM {get;set;} public IList<Point2M> PointsM {get;set;}=new List<Point2M>(); }
public sealed class ContoursResultV0 { public bool Available {get;set;} public bool Complete {get;set;} public string Method=>"marching_squares_linear_interpolation_v1"; public IList<double> GeneratedLevelsMinutes {get;set;}=new List<double>(); public int ContourCount=>Contours.Count; public int ClosedContourCount=>Contours.Count(x=>x.Closed); public int OpenContourCount=>Contours.Count(x=>!x.Closed); public IList<ContourV0> Contours {get;set;}=new List<ContourV0>(); public IList<string> Blockers {get;set;}=new List<string>(); public IList<string> Warnings {get;set;}=new List<string>{"Contour levels are technical/diagnostic time levels, not statutory thresholds."}; public bool PermitReadyCertified=>false; }
public sealed class ForwardVerticalSliceResultV0 { public bool Available {get;set;} public bool Complete {get;set;} public string Scope=>"compiled_forward_vertical_slice_v0_convex_prism"; public SolarResultV0 Solar {get;set;}=new SolarResultV0(); public ShadowSlicesResultV0 ShadowSlices {get;set;}=new ShadowSlicesResultV0(); public DurationResultV0 Duration {get;set;}=new DurationResultV0(); public ContoursResultV0 Contours {get;set;}=new ContoursResultV0(); public IList<string> Blockers {get;set;}=new List<string>(); public IList<string> Warnings {get;set;}=new List<string>(); public bool PermitReadyCertified=>false; }

public static class ForwardVerticalSliceV0
{
 public static ForwardVerticalSliceResultV0 Run(ForwardVerticalSliceInputV0 input)
 {
  var r=new ForwardVerticalSliceResultV0(); Validate(input,r.Blockers); if(r.Blockers.Count>0)return r;
  BuildSolar(input,r.Solar); if(!r.Solar.Complete){Copy(r.Solar.Blockers,r.Blockers);return r;}
  foreach(var s in r.Solar.Samples){var dz=input.Caster.TopZM-input.MeasurementPlaneElevationM;var dx=dz*s.ShadowLengthFactor*s.ShadowDirectionModel.X;var dy=dz*s.ShadowLengthFactor*s.ShadowDirectionModel.Y;var points=input.Caster.FootprintPointsM.Select(p=>new Point2M(p.X,p.Y)).Concat(input.Caster.FootprintPointsM.Select(p=>new Point2M(p.X+dx,p.Y+dy)));var hull=ForwardGeometryV0.Hull(points);r.ShadowSlices.Slices.Add(new ShadowSliceV0{SliceIndex=s.SampleIndex,TrueSolarMinutes=s.TrueSolarMinutes,Polygons=new List<ShadowPolygonV0>{new ShadowPolygonV0{PointsM=hull}}});}
  r.ShadowSlices.Available=r.ShadowSlices.Complete=true;
  BuildDuration(input,r.ShadowSlices,r.Duration);if(!r.Duration.Complete){Copy(r.Duration.Blockers,r.Blockers);return r;}
  BuildContours(input.ContourLevelsMinutes,r.Duration,r.Contours);if(!r.Contours.Complete){Copy(r.Contours.Blockers,r.Blockers);return r;}
  r.Available=r.Complete=true;return r;
 }
 static void Copy(IList<string> a,IList<string>b){foreach(var x in a)b.Add(x);}
 static void Validate(ForwardVerticalSliceInputV0? i,IList<string>b)
 {
  if(i==null){b.Add("input_required");return;}if(!ForwardGeometryV0.Finite(i.LatitudeDeg)||i.LatitudeDeg < -90||i.LatitudeDeg>90)b.Add("invalid_latitude");if(!ForwardGeometryV0.Finite(i.SolarDeclinationDeg))b.Add("invalid_solar_declination");if(!ForwardGeometryV0.Finite(i.TrueNorthDeg))b.Add("invalid_true_north");if(!ForwardGeometryV0.Finite(i.TrueSolarStartMinutes)||!ForwardGeometryV0.Finite(i.TrueSolarEndMinutes)||i.TrueSolarEndMinutes<=i.TrueSolarStartMinutes)b.Add("invalid_time_range");if(!ForwardGeometryV0.Finite(i.SunTimeStepMinutes)||i.SunTimeStepMinutes<=0)b.Add("invalid_sun_time_step");if(!ForwardGeometryV0.Finite(i.MeasurementPlaneElevationM))b.Add("invalid_measurement_plane");if(!ForwardGeometryV0.Finite(i.GridResolutionM)||i.GridResolutionM<=0)b.Add("invalid_grid_resolution");if(!ForwardGeometryV0.Finite(i.AnalysisMarginM)||i.AnalysisMarginM<0)b.Add("invalid_analysis_margin");if(i.MaxGridPoints<=0)b.Add("invalid_max_grid_points");if(i.ContourLevelsMinutes==null||i.ContourLevelsMinutes.Any(x=>!ForwardGeometryV0.Finite(x)||x<=0)||i.ContourLevelsMinutes.Distinct().Count()!=i.ContourLevelsMinutes.Count)b.Add("invalid_contour_levels");
  var c=i.Caster;if(c==null){b.Add("caster_required");return;}if(!ForwardGeometryV0.Finite(c.BaseZM)||!ForwardGeometryV0.Finite(c.TopZM)||c.BaseZM>i.MeasurementPlaneElevationM)b.Add("caster_base_above_measurement_plane");if(c.TopZM<=i.MeasurementPlaneElevationM)b.Add("caster_top_not_above_measurement_plane");var p=c.FootprintPointsM;if(p==null||p.Count<3){b.Add("footprint_requires_three_points");return;}if(p.Any(q=>q==null||!ForwardGeometryV0.Finite(q.X)||!ForwardGeometryV0.Finite(q.Y))){b.Add("invalid_footprint_coordinate");return;}if(p.Select(q=>q.X.ToString("R")+","+q.Y.ToString("R")).Distinct().Count()!=p.Count)b.Add("duplicate_footprint_point");var area=ForwardGeometryV0.SignedArea(p);if(Math.Abs(area)<=ForwardGeometryV0.Epsilon)b.Add("zero_area_footprint");var sign=0;for(var j=0;j<p.Count;j++){var cross=ForwardGeometryV0.Cross(p[j],p[(j+1)%p.Count],p[(j+2)%p.Count]);if(Math.Abs(cross)<=ForwardGeometryV0.Epsilon){b.Add("degenerate_footprint");break;}var now=cross>0?1:-1;if(sign!=0&&now!=sign){b.Add("non_convex_footprint");break;}sign=now;}
  for(var a=0;a<p.Count;a++)for(var z=a+1;z<p.Count;z++){if(z==a+1||(a==0&&z==p.Count-1))continue;if(Intersects(p[a],p[(a+1)%p.Count],p[z],p[(z+1)%p.Count])){b.Add("self_intersecting_footprint");return;}}
 }
 static bool Intersects(Point2M a,Point2M b,Point2M c,Point2M d){var ab1=ForwardGeometryV0.Cross(a,b,c);var ab2=ForwardGeometryV0.Cross(a,b,d);var cd1=ForwardGeometryV0.Cross(c,d,a);var cd2=ForwardGeometryV0.Cross(c,d,b);return ((ab1>0&&ab2<0)||(ab1<0&&ab2>0))&&((cd1>0&&cd2<0)||(cd1<0&&cd2>0));}
 static void BuildSolar(ForwardVerticalSliceInputV0 i,SolarResultV0 r)
 {
  var times=new List<double>{i.TrueSolarStartMinutes};for(var t=i.TrueSolarStartMinutes+i.SunTimeStepMinutes;t<i.TrueSolarEndMinutes-1e-9;t+=i.SunTimeStepMinutes)times.Add(t);if(Math.Abs(times[times.Count-1]-i.TrueSolarEndMinutes)>1e-9)times.Add(i.TrueSolarEndMinutes);
  for(var n=0;n<times.Count;n++){var minute=times[n];var ha=15*(minute/60-12);var lat=Rad(i.LatitudeDeg);var dec=Rad(i.SolarDeclinationDeg);var h=Rad(ha);var sin=Math.Sin(lat)*Math.Sin(dec)+Math.Cos(lat)*Math.Cos(dec)*Math.Cos(h);sin=Math.Max(-1,Math.Min(1,sin));var alt=Math.Asin(sin);var altDeg=Deg(alt);if(altDeg<=0){r.Blockers.Add("solar_sample_at_or_below_horizon");return;}var az=(Deg(Math.Atan2(Math.Sin(h),Math.Cos(h)*Math.Sin(lat)-Math.Tan(dec)*Math.Cos(lat))+Math.PI)+360)%360;var shadow=(az+180)%360;var model=(shadow+i.TrueNorthDeg)%360;if(model<0)model+=360;r.Samples.Add(new SolarSampleV0{SampleIndex=n,TrueSolarMinutes=minute,SolarAltitudeDeg=altDeg,SolarAzimuthDeg=az,ShadowAzimuthTrueNorthDeg=shadow,ShadowAzimuthModelDeg=model,ShadowLengthFactor=1/Math.Tan(alt),ShadowDirectionModel=new Point2M(Math.Sin(Rad(model)),Math.Cos(Rad(model)))});}
  r.Available=r.Complete=true;
 }
 static double Rad(double d)=>d*Math.PI/180;static double Deg(double r)=>r*180/Math.PI;
 static void BuildDuration(ForwardVerticalSliceInputV0 i,ShadowSlicesResultV0 slices,DurationResultV0 r)
 {
  var pts=slices.Slices.SelectMany(s=>s.Polygons).SelectMany(p=>p.PointsM).ToList();var minx=pts.Min(p=>p.X)-i.AnalysisMarginM,miny=pts.Min(p=>p.Y)-i.AnalysisMarginM,maxx=pts.Max(p=>p.X)+i.AnalysisMarginM,maxy=pts.Max(p=>p.Y)+i.AnalysisMarginM;var nx=(int)Math.Ceiling((maxx-minx)/i.GridResolutionM)+1;var ny=(int)Math.Ceiling((maxy-miny)/i.GridResolutionM)+1;var count=(long)nx*ny;r.GridPointCount=count>int.MaxValue?int.MaxValue:(int)count;if(count>i.MaxGridPoints){r.Blockers.Add("max_grid_points_exceeded");return;}r.SpatialResolutionM=i.GridResolutionM;r.TemporalStepMinutes=slices.Slices.Skip(1).Select((s,k)=>s.TrueSolarMinutes-slices.Slices[k].TrueSolarMinutes).Distinct().Count()==1?slices.Slices[1].TrueSolarMinutes-slices.Slices[0].TrueSolarMinutes:(double?)null;r.GridSpec=new GridSpecV0{OriginXM=minx,OriginYM=miny,ResolutionM=i.GridResolutionM,XCount=nx,YCount=ny,MaxXM=minx+(nx-1)*i.GridResolutionM,MaxYM=miny+(ny-1)*i.GridResolutionM};
  for(var y=0;y<ny;y++)for(var x=0;x<nx;x++){var px=minx+x*i.GridResolutionM;var py=miny+y*i.GridResolutionM;var states=slices.Slices.Select(s=>ForwardGeometryV0.Contains(s.Polygons[0].PointsM,px,py)?1:0).ToList();double duration=0;for(var k=0;k<states.Count-1;k++)duration+=(slices.Slices[k+1].TrueSolarMinutes-slices.Slices[k].TrueSolarMinutes)*(states[k]+states[k+1])/2.0;r.DurationValues.Add(new DurationPointV0{X=px,Y=py,ShadowDurationMinutes=duration});}
  r.MaximumShadowDurationMinutes=r.DurationValues.Max(x=>x.ShadowDurationMinutes);r.ShadowedPointCount=r.DurationValues.Count(x=>x.ShadowDurationMinutes>0);r.Available=r.Complete=true;
 }
 static void BuildContours(IList<double> levels,DurationResultV0 d,ContoursResultV0 r)
 {
  var g=d.GridSpec!;foreach(var level in levels.OrderBy(x=>x)){var segments=new List<Tuple<Point2M,Point2M>>();for(var iy=0;iy<g.YCount-1;iy++)for(var ix=0;ix<g.XCount-1;ix++){var ids=new[]{iy*g.XCount+ix,iy*g.XCount+ix+1,(iy+1)*g.XCount+ix+1,(iy+1)*g.XCount+ix};var c=ids.Select(id=>d.DurationValues[id]).ToArray();Cell(c,level,segments);}var lines=Stitch(segments);var index=0;foreach(var line in lines){double length=0;for(var j=0;j<line.Count-1;j++)length+=Math.Sqrt(Math.Pow(line[j+1].X-line[j].X,2)+Math.Pow(line[j+1].Y-line[j].Y,2));r.Contours.Add(new ContourV0{LevelMinutes=level,ContourIndex=index++,Closed=line.Count>2&&Key(line[0])==Key(line[line.Count-1]),LengthM=length,PointsM=line});}if(lines.Count>0)r.GeneratedLevelsMinutes.Add(level);}r.Available=r.Complete=true;
 }
 static Point2M Inter(DurationPointV0 a,DurationPointV0 b,double l){var delta=b.ShadowDurationMinutes-a.ShadowDurationMinutes;var t=Math.Abs(delta)<=1e-9?.5:(l-a.ShadowDurationMinutes)/delta;t=Math.Max(0,Math.Min(1,t));return new Point2M(a.X+t*(b.X-a.X),a.Y+t*(b.Y-a.Y));}
 static void Cell(DurationPointV0[] c,double l,List<Tuple<Point2M,Point2M>> s){var edges=new[]{Tuple.Create(0,1),Tuple.Create(1,2),Tuple.Create(2,3),Tuple.Create(3,0)};var active=new List<int>();var p=new Dictionary<int,Point2M>();for(var e=0;e<4;e++)if((c[edges[e].Item1].ShadowDurationMinutes>=l)!=(c[edges[e].Item2].ShadowDurationMinutes>=l)){active.Add(e);p[e]=Inter(c[edges[e].Item1],c[edges[e].Item2],l);}if(active.Count==2){s.Add(Tuple.Create(p[active[0]],p[active[1]]));return;}if(active.Count!=4)return;var code=Enumerable.Range(0,4).Sum(k=>c[k].ShadowDurationMinutes>=l?1<<k:0);var high=c.Average(x=>x.ShadowDurationMinutes)>=l;var pairs=(code==5&&high)||(code==10&&!high)?new[]{Tuple.Create(0,1),Tuple.Create(2,3)}:new[]{Tuple.Create(0,3),Tuple.Create(1,2)};foreach(var pair in pairs)s.Add(Tuple.Create(p[pair.Item1],p[pair.Item2]));}
 static string Key(Point2M p)=>Math.Round(p.X,10).ToString("R")+","+Math.Round(p.Y,10).ToString("R");
 static List<IList<Point2M>> Stitch(List<Tuple<Point2M,Point2M>> segs){var edge=new SortedDictionary<string,Tuple<Point2M,Point2M>>();foreach(var e in segs){var ka=Key(e.Item1);var kb=Key(e.Item2);if(ka==kb)continue;edge[string.CompareOrdinal(ka,kb)<0?ka+"|"+kb:kb+"|"+ka]=e;}var adj=new SortedDictionary<string,List<string>>();var points=new Dictionary<string,Point2M>();foreach(var e in edge.Values){var a=Key(e.Item1);var b=Key(e.Item2);points[a]=e.Item1;points[b]=e.Item2;if(!adj.ContainsKey(a))adj[a]=new List<string>();if(!adj.ContainsKey(b))adj[b]=new List<string>();adj[a].Add(b);adj[b].Add(a);}foreach(var x in adj.Values)x.Sort(StringComparer.Ordinal);var unused=new SortedSet<string>(edge.Keys,StringComparer.Ordinal);var lines=new List<IList<Point2M>>();while(unused.Count>0){var endpoint=adj.Keys.Where(k=>adj[k].Count(n=>unused.Contains(string.CompareOrdinal(k,n)<0?k+"|"+n:n+"|"+k))==1).FirstOrDefault();var start=endpoint??unused.Min!.Split('|')[0];var line=new List<Point2M>{points[start]};string? previous=null,current=start;while(true){var next=adj[current].FirstOrDefault(n=>n!=previous&&unused.Contains(string.CompareOrdinal(current,n)<0?current+"|"+n:n+"|"+current));if(next==null)break;unused.Remove(string.CompareOrdinal(current,next)<0?current+"|"+next:next+"|"+current);line.Add(points[next]);previous=current;current=next;if(current==start)break;}if(line.Count>1)lines.Add(line);}return lines.OrderBy(x=>Key(x[0]),StringComparer.Ordinal).ThenBy(x=>x.Count).ToList();}
}
