"""Projection-only parity fixture generated by the canonical Python pipeline."""
import json
from pathlib import Path

from shadow_projection import _build_convex_shadow_envelope_v0, _project_point
from shadow_sun import _sun_position_for_true_solar_minutes

FIXTURE = Path(__file__).parents[1] / "fixtures" / "parity" / "forward_projection_v0.json"


def _reference_slices(fixture, footprint):
    slices = []
    solar_input = fixture["solar"]
    for minute in fixture["true_solar_minutes"]:
        solar = _sun_position_for_true_solar_minutes(
            minute,
            solar_input["latitude_deg"],
            solar_input["solar_declination_deg"],
            solar_input["true_north_deg"],
        )
        direction = solar["shadow_direction_model"]
        projected = []
        for point in footprint:
            projected.append({
                "x_m": point["x"], "y_m": point["y"],
                "z_m": fixture["measurement_plane_elevation_m"],
            })
            result = _project_point(
                {"x_m": point["x"], "y_m": point["y"], "z_m": fixture["top_z_m"]},
                fixture["measurement_plane_elevation_m"],
                {"x_east": direction["x"], "y_north": direction["y"]},
                solar["shadow_length_factor"],
            )
            projected.append(result["projected_point_m"])
        envelope = _build_convex_shadow_envelope_v0(
            projected, fixture["measurement_plane_elevation_m"]
        )
        slices.append({
            "true_solar_minutes": minute,
            "points_m": [
                {"x": point["x_m"], "y": point["y_m"]}
                for point in envelope["hull_points_m"]
            ],
        })
    return slices


def _canonical_polygon(points):
    """Compare physical polygons independently of start vertex and winding."""
    rounded = [(round(point["x"], 6), round(point["y"], 6)) for point in points]
    rotations = []
    for ordered in (rounded, list(reversed(rounded))):
        rotations.extend(ordered[index:] + ordered[:index] for index in range(len(ordered)))
    return min(rotations)


def test_forward_projection_fixture_is_canonical_python_output():
    fixture = json.loads(FIXTURE.read_text(encoding="utf-8"))
    for case in fixture["cases"]:
        assert case["shadow_slices"] == _reference_slices(fixture, case["footprint_points_m"])


def test_footprint_winding_has_equivalent_world_coordinate_projection():
    fixture = json.loads(FIXTURE.read_text(encoding="utf-8"))
    ccw, cw = fixture["cases"]
    for ccw_slice, cw_slice in zip(ccw["shadow_slices"], cw["shadow_slices"]):
        assert _canonical_polygon(ccw_slice["points_m"]) == _canonical_polygon(cw_slice["points_m"])

    all_points = [point for item in ccw["shadow_slices"] for point in item["points_m"]]
    assert min(point["x"] for point in all_points) > 100.0
    assert max(point["y"] for point in all_points) < -50.0

    footprint_x = [point["x"] for point in ccw["footprint_points_m"]]
    morning, noon, afternoon = ccw["shadow_slices"]
    assert min(point["x"] for point in morning["points_m"]) < min(footprint_x)
    assert max(point["x"] for point in noon["points_m"]) > max(footprint_x)
    assert max(point["x"] for point in afternoon["points_m"]) > max(point["x"] for point in noon["points_m"])
